### ISSUE TITLE
ignore_strings is passed to gsub with perl = TRUE 

### ISSUE THREAD

**Issue by KiprasKancys** [ChrisMuir/refinr#12]
Hi, 
Thanks for the package :) 

I noticed that in `key_collision_merge()` you remove ignore strings with `remove_strings` function which is fine. But in `n_gram_merge()` you use `gsub` with `perl = TRUE` which makes a mess if you have some kind of regex pattern between your ignore_strings. 

In my case I was generating ignore strings from text so I got all kind of things like '+' , '.', ect... 

Error message if I pass '+' in ignore_strings
```
key_collision_merge(c('aa+', 'aa'), ignore_strings = '+') # works fine
n_gram_merge(c('aa+', 'aa'), ignore_strings = '+') # crashes
Error in gsub(regex, "", vect, perl = TRUE) : 
  invalid regular expression '\b(+|inc|corp|co|llc|ltd|div|ent|lp|and)\b| '
```
I can clean ignore_strings myself, but that is something to consider for the package too, maybe use  `remove_strings` in both cases?

**Comment by ChrisMuir** [comment]
Ah interesting, thank you for pointing this out! I will mess around with this after work today, should be able to push a bug fix tonight.

**Comment by ChrisMuir** [comment]
Hey, so sorry for never following up on this.

One thing to point out, you actually don't need to specify special characters in the `ignore_strings` arg. For example, this:
```r
n_gram_merge(c('aa!@#$%^&*()', 'aa'))
```
Returns this:
```
#> [1] "aa" "aa"
```
Those characters are ignored by default during the grouping and merging.

I'm closing this issue for now, if you have any additional questions on this please post here.
