### ISSUE TITLE
bus_suffix question

### ISSUE THREAD

**Issue by poldham** [ChrisMuir/refinr#4]
Dear Chris, 

Many thanks for this package. I am trying to write a walkthrough using refinr on matching author and inventor names and will then move on to organisation names. I wanted to ask whether you could point me to the source of the bus_suffix data. I ask because I can't seem to locate it in the package code (and am possibly being dim). It would be useful to see this in a df (maybe in data) depending on where it comes from. Then users can assess the coverage. 

Thanks again for the package!

Best, 

Paul

**Comment by ChrisMuir** [comment]
Hi Paul,

Sure thing, the function `business_suffix()` handles all of the transformations (given that input arg `bus_suffix` is `TRUE`). That func is located in the [utils.R](https://github.com/ChrisMuir/refinr/blob/master/R/utils.R) file, here's the guts:
```r
# Function that attempts to merge common business name suffixes within a
# character string.
business_suffix <- function(vect) {
  vect <- gsub(" incorporated| incorporate", " inc", vect, perl = TRUE)
  vect <- gsub(" corporation| corporations", " corp", vect, perl = TRUE)
  vect <- gsub(" company| companys| companies", " co", vect, perl = TRUE)
  vect <- gsub(" limited liability co", " llc", vect, fixed = TRUE)
  vect <- gsub(" limited$", " ltd", vect, perl = TRUE)
  vect <- gsub(" division| divisions", " div", vect, perl = TRUE)
  vect <- gsub(" enterprises| enterprise", " ent", vect, perl = TRUE)
  vect <- gsub(" limited partnership", " lp", vect, fixed = TRUE)
  vect <- gsub(" and ", " & ", vect, fixed = TRUE)
  return(vect)
}
```
I like the idea of making the transformations easily accessible to users, I hadn't considered that before, thank you for that suggestion. I'll give that some thought and will probably work on it in the next week or two.

Oh and if you make a walk-through and it's public, please send me a link if you think about it! I'd love to see it.

Thanks again for the suggestion!

**Comment by poldham** [comment]
Hi Chris, thanks very much. I looked in .zzz but not in utils!  I could see potential for this approach to expand in a number of different directions. For example there are quite a range of different company suffixes that could be added (and I will look into the work done on that). Also In the data coming back from the scientific literature University is commonly reduced to Univ and so on. 

I wanted to mention that the [countrycode](https://github.com/vincentarelbundock/countrycode) package has adopted the approach of allowing the submission of custom dictionaries. That might be an option to consider. 

I will let you know when the walk through is done. 

All the best, 

Paul

**Comment by ChrisMuir** [comment]
What you're describing sounds like what the arg `ignore_strings` is designed to handle. It lets the user pass a vector of substrings to "ignore" during the clustering process....those substrings are simply removed from each string during the `get_fingerprint` step (prior to creating clusters).

Check out the pkg [vignette](https://cran.r-project.org/web/packages/refinr/vignettes/refinr-vignette.html) for some examples of using arg `ignore_strings`.

If you had something different in mind, please let me know!

**Comment by poldham** [comment]
Thanks Chris, I had spotted ignore_strings and will experiment and see how it goes. All the best, Paul
